module.exports.studentController=require('./students')
module.exports.authController=require('./auth')
module.exports.teacherController=require('./teachers')
module.exports.parentController=require('./parents')
module.exports.standardController=require('./standard')
module.exports.subjectController=require('./subjects')
module.exports.discussionForumController=require('./discussionForum')